import type { Metadata } from "next";
import "@/app/_styles/globals.css";
import { Layout } from "@/app/_components/Layout/Layout";
import { BlastProvider } from "@/app/_provider/blastProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <BlastProvider>
          <Layout>{children}</Layout>
        </BlastProvider>
      </body>
    </html>
  );
}
